### ISSUE TITLE
IPMapVisulaiser Submission

### ISSUE THREAD

**Issue by thomphil** [CodingGarden/seedling-school-01-frontend-project#3]
## Project Name / Title
IPMapVisualiser

## Your Name / Title
thomphill

## Project Description
Shows the location of an IP address on a map.

Enter an IP address and click 'Find' to search for its location.
https://github.com/thomphil/IPMapVisualiser

## What 3rd Party Web API do you plan to use?
IP Vigilante 
* Link to the API documentation here:
https://www.ipvigilante.com/api-developer-docs/

## Which of the following describes you:

* [x] YouTube Subscriber
* [x] Twitch Follower
* [ ] Patreon Patron
* [ ] Superchat Donor
* [ ] Streamlabs Donor
* [ ] Coding Garden Moderator

**Comment by w3cj** [comment]
I like it! If leaflet doesn't work for you, you can try mapbox, they have a pretty good free tier.

As a stretch feature, you might try finding an API that will automatically get a users IP address so they can click a button like "What's my IP?" Or "Find me on the map"

Looks good overall. Go ahead and get started!

**Comment by w3cj** [comment]
How is the project going so far? Any updates?

**Comment by thomphil** [comment]
I was having issues with a CORS error but this seemed to be due to IPVigilante API so I've started using IP-API and it's been a lot more smooth sailing. I'm successfully logging the JSON response.

In regard to your suggestion to use mapbox, it looks like I'm going to have to use an API key, shall I just post it publicly? or am I missing a trick here?

**Comment by thomphil** [comment]
The event listener error seems to be something to do with the sequence of the main.js (containing the above code snippet) and the html file are being loaded, as I can successfully run the above code in the console after the page has loaded.

**Comment by thomphil** [comment]
Yeeees, resolved by wrapping it with window.onload

**Comment by w3cj** [comment]
It looks like you found another API that does not have the cors issue?

For mapbox, the API key is meant to be public. There is no way to hide keys in front-end code.

**Comment by w3cj** [comment]
Any updates to share?

**Comment by w3cj** [comment]
Any updates to share?
