### ISSUE TITLE
<Countries> Project Submission

### ISSUE THREAD

**Issue by rafael-almeida** [CodingGarden/seedling-school-01-frontend-project#31]
## Project Name / Title

> Countries

## Your Name / Title

> Rafael / etts

## Project Description

> A web app built with Vanilla JavaScript for displaying info about countries, filtered by region and/or name.

* Link to your Github repo/project description file:
https://github.com/ralmeida094/countries

## What 3rd Party Web API do you plan to use?

* Link to the API documentation here:
https://restcountries.eu/

## Which of the following describes you:

* [x] YouTube Subscriber
* [x] Twitch Follower
* [ ] Patreon Patron
* [ ] Superchat Donor
* [ ] Streamlabs Donor
* [ ] Coding Garden Moderator

**Comment by rafael-almeida** [comment]
I still have somethings to work out, but I would love to get your feedback. 
I didn't include the wireframes because I ended up using a design I found online (link is in the repo). 
Thank you!

**Comment by w3cj** [comment]
Looks great! Feel free to get started.

**Comment by rafael-almeida** [comment]
Thanks! Project is online [here](https://ralmeida094.github.io/countries)

**Comment by mahendrjy** [comment]
I like it, It's amazing.

**Comment by rafael-almeida** [comment]
> I like it, It's amazing.

Thank you!

**Comment by w3cj** [comment]
Any updates to share? Let me know if you would like a ui review or code review.

**Comment by rafael-almeida** [comment]
> Any updates to share? Let me know if you would like a ui review or code review.

Hey CJ,
I haven't been able to work on the project because of finals in school, but I think all JS that I need is done. The rest should be plain CSS. 
I would like a code review.
Thank you!!
