### ISSUE TITLE
Personal portfolio

### ISSUE THREAD

**Issue by ghost** [CodingGarden/seedling-school-01-frontend-project#35]
## Tombstone01 | Personal portfolio

> Give your project a good descriptive name

Personal portfolio

## Mr Kananelo Maxwell

> What should we call you?

DeepSense6 / Max / tombstone01

## Project Description

This is my personal website. I use it to communicate my work with potential employers. In the website I have a little story about myself, contact information, applications that I have build, gists and github repositories

[Live version](http://www.tombstone01.com)
[Github repo](https://github.com/Tombstone01/tombstone-heroku)

## What 3rd Party Web API do you plan to use?

I don't know if I need an API for a portfolio, but I'm open to ideas!

## Which of the following describes you:

* [x] YouTube Subscriber
* [x] Twitch Follower
* [ ] Patreon Patron
* [ ] Superchat Donor
* [ ] Streamlabs Donor
* [ ] Coding Garden Moderator

**Comment by w3cj** [comment]
Hey! The issues here are specifically for projects related to the project described in the readme: https://github.com/CodingGarden/seedling-school-01-frontend-project

You can see example project ideas there and a list of requirements / goals for the project.

You can see a video overview of the project here: https://www.youtube.com/watch?v=avZiet2DY9Y

The main idea for this is to create projects that you could list in your portfolio. So I don't think a portfolio site itself is a good project for this. 😁

Closing this issue. Feel free to open a new one if you have a project idea!
