### ISSUE TITLE
Need help with UI loading image

### ISSUE THREAD

**Issue by ScottRoberson** [CodingGarden/seedling-school-01-frontend-project#36]
I am nearing the end of the project and I am having a little trouble with the API data loading on the page before my loading image clears. Is there a way to delay the fetched data to display while the image stays on the screen? I have tried a timeout on the hide but the data loads in behind it. Here is a link to my code if it is needed for reference. 

https://github.com/ScottRoberson/Gif-land

**Comment by w3cj** [comment]
Please use your existing issue to ask for help. Closing this one.
